### ISSUE TITLE
Stuck at Status: Busy after the latest game update (Orryx 1.10 EGS)

### ISSUE THREAD

**Issue by csuklyaspatkany** [Sheep-y/Modnix#35] opened 2021-02-03 06:29 UTC
[Modnix Log 2021-02-03 07-16-10Z.txt](https://github.com/Sheep-y/Modnix/files/5916500/Modnix.Log.2021-02-03.07-16-10Z.txt)

I'm trying with Modnix v3b2, both the installer and manual setup produce the issue. The log is from the manual one. This is a fresh install, no mods installed/loaded.
Game version is Orryx 1.10 EGS. I have tried the troubleshooting guide (restart, verify/reinstall the game, disable antivirus, run everything as admin).
OS is Windows 10 Version 20H2 (OS Build 19042.746), with the latest stable channel updates.

After launching as Administrator, the Status is stuck at busy, and I get this exception (full log attached):

07:16:06.9035 Thread4┊Loader┊GameVer1: opcode 2 <> 8
07:16:06.9045 Thread4┊System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Version.Parse(String input)
   at Sheepy.Modnix.MainGUI.AppControl.CheckGameVersion()
   at Sheepy.Modnix.MainGUI.AppControl.CheckStatus()
07:16:07.1762 Thread4┊Creating sandbox

After this nothing happens, waited ~10 minutes.

**Comment by Sheep-y** [comment] 2021-02-03 13:04
Thanks and confirmed.  The cause of the issue is found and will be fixed, after I take care of some Real Life issues.
Meanwhile, Modnix 2 seems to still work, and manual setup for Modnix 3 is still working but you'll need to manually launch the game.

The reason that Modnix 2 works while Modnix 3 doesn't is partly because of the removal of the injector.  The game version routine changed again, causing an error when detecting game version.  In Mx3 the Injector would catch the error, in Mx3 it now escalates and prevents the status checker thread to report "all green".

**Comment by csuklyaspatkany** [comment] 2021-02-03 14:50
Hi @Sheep-y and thanks. Haven't checked version 2, will try tomorrow, take your time with the fix, IRL is ever more important. BTW, a lot of the UI elements stay disabled besides the Busy status: 
![image](https://user-images.githubusercontent.com/78465898/106763605-49a95280-6637-11eb-8667-4905c85dd6e9.png)

Setup, Launch, Run EXE, Add Mod all stay disabled.

**Comment by Sheep-y** [comment] 2021-02-04 04:15
Yes, it is designed to do that.  Because it'd be problematic if you launch game while Modnix is busy scanning the game to find its versions and mod compatibilities.   It's arguably outdated since Modnix 3 no longer modify game files with injector, and I plan to touch the workflow until Modnix 4.

Meanwhile, the issue is fixed in commit c677e0ee5a50a037ebf0492fb4cf0ba9c00ba988 and ea942ae58e18ce3b123cefe5f25011823867f0f7, and released with [Modnix 3 Beta 3](https://github.com/Sheep-y/Modnix/releases/tag/v3.0.2021.0204).

**Closed by Sheep-y** 2021-02-04 04:15 UTC
Labels: bug
